CREATE TABLE "cities" (
    "CITY_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "CITY_NAME" TEXT NOT NULL DEFAULT ('Unsorted'),
    "CITY_STATE" TEXT
);
CREATE UNIQUE INDEX "CITY_ID" on cities (CITY_ID ASC);
CREATE UNIQUE INDEX "CITY_NAME_STATE" on cities (CITY_NAME ASC, CITY_STATE ASC);

CREATE TABLE "stations" (
    "STATION_ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "STATION_NAME" TEXT NOT NULL,
    "CITY_ID" REFERENCES cities("CITY_ID")
);
CREATE UNIQUE INDEX "STATION_ID" on stations (STATION_ID ASC);
CREATE UNIQUE INDEX "STATION_NAME" on stations (STATION_NAME ASC);

CREATE TABLE "feeds" (
    "FEED_PK" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "FEED_ID" INTEGER NOT NULL,
    "STATION_ID" REFERENCES stations("STATION_ID"),
   /* "STATION_ID" INTEGER NOT NULL, */
    "FEED_NAME" TEXT NOT NULL,
    "FEED_URL" TEXT NOT NULL,
    "FEED_RESOLUTION" TEXT,
    "FEED_BANDWIDTH" INTEGER,
    "FEED_CODECS" TEXT,
    /*Video feed protection schemes may require the stream to be processed through
     an external daemon before playback is possible.*/
    "FEED_REQUIRES_PROXY" INTEGER DEFAULT ('0'),
    "EXTRA_INFO" TEXT
);
CREATE UNIQUE INDEX "FEED_PK" on feeds (FEED_PK ASC);
CREATE INDEX "FEED_ID" on feeds (FEED_ID ASC);
CREATE UNIQUE INDEX "FEED_URL" on feeds (FEED_URL ASC);

/* Default city for unsorted stations */
INSERT INTO cities (CITY_NAME, CITY_STATE) values ("Unsorted", "Unsorted");
